### ISSUE TITLE
HOW THE FUCK DO YOU USE THIS?????

### ISSUE THREAD

**Issue by Str4nd3r666** [Tripp-omg/Safety-Checker#1]
I don't know coding, how the fuck do i use this, there's not even a god damn tutorial that comes with it. The fucking instructions are shitty and aren't well constructed. Please fucking ELABORATE?????

**Comment by Tripp-omg** [comment]
why are u on github if u can't even understand how to run files

**Comment by cfuendev** [comment]
@Str4nd3r666 Regardless of the fact that your issue title and description use a lot of swears and should be more respectful, you are asking a legitimate question and pointing out a problem that this repo has, which the mantainer of this repository has failed to address by either updating their repository to include instructions, explaining the steps or pointing you at a guide or materials that could help you get the python code running.

I'll give you a little walk-through! You have two options, you can:

**Option 1 - Use an online coding/computing platform like [Replit](https://replit.com/)**

All you have to do is [create a Repl based on this repository](https://docs.replit.com/replit-workspace/using-git-on-replit/running-github-repositories-replit) which is just a little online workspace/playground that allows you to write and run Python Code that is inside this repo. I do not recommend Replit since it can get janky, specially when working with GitHub repositories, but it's possible to clone all the files from here into a Repl, which is much faster. I think running python3 in the integrated console followed by the name of the mail file `python3 safetyChecker.py` should work, but if that doesn't work, leave another response here and I'll get back at you asap!

**Option 2 - Manually download the Python interpreter, clone the files to your computer and run the code**

This one has a few steps, but it might be worth it and let you run the code more comfortably once you got it all set up.

1. Download and install the Python interpreter from the [official site](https://www.python.org/downloads/). If I'm not wrong you simply have to click "Next" on the installer and such, as you would do with most installation wizards. When you're done, the Python interpreter and Command Line should be installed in your machine. All of this code is written in Python, a very popular and simple programming language.
2. Download all the files on this repository to make sure the script works (This is easier if you use GUI software like [GitHub Desktop](https://desktop.github.com/download/) to [clone the repository to your machine's disk via their application](https://docs.github.com/en/desktop/adding-and-cloning-repositories/cloning-a-repository-from-github-to-github-desktop), since otherwise you'd have to install software like [Git](https://git-scm.com/), which only works on the command line.
3. Open up a `cmd` command line instance (I'm assuming you're on Windows) so you can enter the location of the repository files and run the python code.
<img src="https://static1.howtogeekimages.com/wordpress/wp-content/uploads/2017/02/650x268xWindows_04.jpg?q=50&fit=crop&w=825&dpr=1.5" width="500px">
4. set the current working directory (cwd for short) to the directory you cloned the files in. If it was something like...

```
C:/users/str4nd3r/new_folder/Safety-Checker
```
then you must use the `cd` command like...
```
cd C:/users/str4nd3r/new_folder/Safety-Checker
```
5. and finally, run `safetyChecker.py` with the Python interpreter, via the `python3` command, like...
```
python3 safetyChecker.py
```
6. Whatever the script does will happen from this point onwards. Congrats! 🎉

**Comment by cfuendev** [comment]
> why are u on github if u can't even understand how to run files

@Tripp-omg regardless of the language used on the issue title and description, your less hostile but still dismissive response doesn't contribute anything to the accessibility of this repository, and you shouldn't have closed this as completed, since the problem hasn't really been solved. Closing this as completed should've only been done after you either...
- updated your repo to be more useful to non-coders by providing a step-by-step guide in the README (Since most Kruben fans aren't coders or even IT people, which should be obvious)
- pointed at them in the right direction, sharing some videos, documentation or any material that would help them comprehend how to run the code

**Comment by Str4nd3r666** [comment]
Not everyone knows prorgramming> why are u on github if u can't even understand how to run files

**Comment by Str4nd3r666** [comment]
@cfuendev I changed the title of the question to be more appropriate but still you should've helped me at least @Tripp-omg 
Everyone swears in this world, and it doesn't give you a reason to say something as bland as:

**Why are you on github if don't know how to run a program.**

This sentence alone just tells everybody that you are ignorant of other people's background. NOT EVERYBODY knows programming. Somebody as me just trying to use a program that you haven't given enough instructions in the readme file doesn't mean that everybody on github knows programming. But of course, you had to talk back in a hostile way, instead of guiding me through it. You were the one who made the program and decided to give very vague instructions of about 3 steps thinking everybody knew programming and actually knew how to run it. After this, i had to ask chatgpt multiple times to explain me things that i didn't know shit about, nor knew how to use it, which took me about 40 minutes to figure out. If you just had put clearer and precise instructions, i would not have been there.

IN FACT, this situation is the same thing as if it was my first basketball practise and you were my coach. You then told me very vague instructions like:

**Just do this move.**

Without even showing me a tutorial or even doing a demonstration yourself.

And then i got furious because i couldn't do the certain move and then came up to you and furiously yelled at you:

**HOW DO YOU DO THIS?!?!**

Yes, i know that my response wasn't respectful whatsoever but the least you could've done is:

1. Make your instructions clearer
2. Instead of responding like you did, at least help.

But instead responded with:

**Why are you doing basketball if you can't even do this certain move?**

Like if you were expecting me to know every move in basketball. Despite the fact of me swearing a lot, you could've helped me, but you didn't.

**Comment by Str4nd3r666** [comment]
@cfuendev I changed the title of the question to be more appropriate but still you should've helped me at least @Tripp-omg 
Everyone swears in this world, and it doesn't give you a reason to say something as bland as:

**Why are you on github if don't know how to run a program.**

This sentence alone just tells everybody that you are ignorant of other people's background. NOT EVERYBODY knows programming. Somebody as me just trying to use a program that you haven't given enough instructions in the readme file doesn't mean that everybody on github knows programming. But of course, you had to talk back in a hostile way, instead of guiding me through it. You were the one who made the program and decided to give very vague instructions of about 3 steps thinking everybody knew programming and actually knew how to run it. After this, i had to ask chatgpt multiple times to explain me things that i didn't know shit about, nor knew how to use it, which took me about 40 minutes to figure out. If you just had put clearer and precise instructions, i would not have been there.

IN FACT, this situation is the same thing as if it was my first basketball practise and you were my coach. You then told me very vague instructions like:

**Just do this move.**

Without even showing me a tutorial or even doing a demonstration yourself.

And then i got furious because i couldn't do the certain move and then came up to you and furiously yelled at you:

**HOW DO YOU DO THIS?!?!**

Yes, i know that my response wasn't respectful whatsoever but the least you could've done is:

1. Make your instructions clearer
2. Instead of responding like you did, at least help.

But instead responded with:

**Why are you doing basketball if you can't even do this certain move?**

Like if you were expecting me to know every move in basketball. Despite the fact of me swearing a lot, you could've helped me, but you didn't.
